const datosAnimales = [
  "Los flamencos rosados no nacen con ese color sino que sus plumas son grises al nacer y adquieren el tono rosa por comer camarones y algas. Los pulpos tienen tres corazones donde dos bombean sangre a las branquias y el tercero al resto del cuerpo además de que su sangre es azul. Las vacas son animales muy sociales que forman lazos de amistad profundos con otras vacas de su manada y se estresan si las separan. Las huellas dactilares de los koalas son tan parecidas a las humanas que los expertos tienen problemas para diferenciarlas en un microscopio. Las nutrias marinas se toman de las manos fuertemente mientras duermen flotando en el agua para que la corriente no las separe. Los elefantes son los únicos mamíferos que no pueden saltar debido a la estructura de sus huesos y a su gran peso corporal. El rugido de un león adulto es tan potente que puede escucharse a una distancia de hasta ocho kilómetros en la sabana. Las jirafas no tienen cuerdas vocales por lo que se comunican entre ellas mediante sonidos infrasónicos que el oído humano no puede percibir.",
  "Los colibríes son las únicas aves capaces de volar hacia atrás y permanecer suspendidas en el aire en un mismo punto gracias a que sus alas rotan en forma de ocho. Los tiburones no tienen huesos en todo su cuerpo sino que su esqueleto está formado completamente por cartílago lo que los hace mucho más ligeros y flexibles al nadar. Las hormigas no tienen pulmones y respiran a través de pequeños orificios en los costados de sus cuerpos llamados espiráculos además de que nunca duermen de la forma en que los humanos lo hacen. Los camaleones pueden mover sus ojos de manera independiente lo que les permite observar dos direcciones distintas al mismo tiempo y tener un campo visual completo de trescientos sesenta grados.",
  "Las abejas melíferas pueden reconocer rostros humanos individuales y recuerdan las características de una persona durante toda su vida si interactúan con ella frecuentemente. Los caballitos de mar eligen a una pareja para toda la vida y son los machos quienes llevan los huevos en una bolsa incubadora hasta el momento del nacimiento de las crías. Los osos polares tienen la piel completamente negra debajo de su denso pelaje blanco el cual en realidad es transparente y refleja la luz solar para camuflarse en la nieve. Los gatos domésticos comparten el noventa y cinco por ciento de su genoma con los tigres de bengala lo que explica que mantengan conductas de caza idénticas a las de sus parientes salvajes.",
  "Las ballenas azules son los antiguos animales más grandes que jamás hayan habitado la tierra superando el tamaño de los dinosaurios más pesados y el latido de su corazón se puede escuchar a tres kilómetros de distancia. Los pingüinos macho regalan una piedra perfectamente lisa a las hembras como propuesta de emparejamiento y si ella la acepta la coloca en su nido para iniciar una familia juntos. Los perros tienen un sentido del olfato tan desarrollado que pueden detectar sutiles cambios químicos en el cuerpo humano permitiéndoles anticipar ataques de epilepsia o caídas de azúcar. Los murciélagos son los únicos mamíferos capaces de volar de forma activa y controlada ya que otros animales similares solo logran planear de un árbol a otro.",
  "Los cocodrilos no pueden sacar la lengua porque la tienen unida al paladar por una membrana rígida lo que les permite cerrar la garganta herméticamente mientras están sumergidos en el agua esperando a sus presas. Los búhos pueden girar sus cabezas hasta doscientos setenta grados en ambas direcciones debido a una adaptación ósea y vascular única que evita que se interrumpa el flujo de sangre hacia su cerebro. Las ardillas plantan miles de árboles nuevos cada año en los bosques de todo el mundo simplemente porque olvidan el lugar exacto donde enterraron sus reservas de nueces y semillas para el invierno.",
  "Los delfines tienen la capacidad de dormir con un solo ojo abierto y manteniendo una mitad de su cerebro completamente despierta para poder seguir respirando en la superficie y mantenerse alerta ante posibles depredadores. Los caracoles de tierra pueden entrar en un estado de hibernación tan profundo que les permite dormir de forma continua durante un período de hasta tres años si las condiciones climáticas no son lo suficientemente húmedas para sobrevivir. Las cebras tienen un patrón de rayas que es único en cada individuo funcionando de la misma manera que las huellas dactilares humanas además de que les sirve para confundir a las moscas picadoras.",
  "Los canguros rojos utilizan su gran cola musculosa como si fuera una quinta pata ya que al caminar lentamente la apoyan en el suelo junto con sus extremidades delanteras para impulsarse hacia adelante de manera eficiente. Los perezosos tienen un metabolismo tan extremadamente lento que pueden tardar hasta un mes entero en digerir una sola hoja de árbol que hayan consumido en su dieta diaria. Las medusas existen en el planeta tierra desde hace más de quinientos millones de años lo que significa que ya habitaban los océanos mucho antes de la aparición y extinción de los dinosaurios.",
  "Las estrellas de mar no tienen cerebro ni sangre propia sino que filtran el agua de mar a través de su sistema vascular para transportar los nutrientes necesarios a sus órganos principales. Los lobos marinos pueden contener la respiración bajo el agua durante más de diez minutos gracias a la alta concentración de oxígeno en sus músculos y glóbulos rojos. Las ovejas tienen pupilas rectangulares que les otorgan un campo de visión periférica de casi trescientos sesenta grados permitiéndoles detectar depredadores sin mover la cabeza.",
  "Los leopardos de las nieves usan su larga y gruesa cola no solo para mantener el equilibrio en los acantilados rocosos sino también para envolverla alrededor de su rostro y protegerse de las tormentas heladas. Las tarántulas pueden regenerar sus patas perdidas durante el proceso de muda de su exoesqueleto recuperando la extremidad por completo tras varios ciclos. Los hipopótamos producen una sustancia aceitosa de color rojizo a través de su piel que actúa como un protector solar natural y un potente antibiótico contra infecciones.",
  "Las avispas de mar poseen uno de los venenos más letales del mundo capaz de detener un corazón humano en pocos minutos y sus tentáculos pueden llegar a medir hasta tres metros de largo. Los castores tienen dientes frontales que nunca dejan de crecer por lo que necesitan masticar madera constantemente para desgastarlos y mantenerlos en un tamaño manejable. Las luciérnagas brillan gracias a una reacción química interna llamada bioluminiscencia la cual utilizan principalmente como un código de señales para atraer a sus parejas.",
  "Las cabras tienen un equilibrio excepcional debido a la estructura de sus pezuñas partidas y planas que funcionan como ventosas naturales permitiéndoles escalar paredes de presas casi verticales. Los cuervos son capaces de planificar el futuro y guardar herramientas específicas para usarlas más tarde demostrando una inteligencia similar a la de los primates. Los osos hormigueros no tienen dientes pero poseen una lengua de hasta sesenta centímetros de largo cubierta de saliva pegajosa para atrapar miles de insectos en segundos.",
  "Los ajolotes poseen la increíble capacidad de regenerar extremidades completas órganos internos e incluso partes de su cerebro y corazón sin dejar ninguna cicatriz visible en el proceso. Las mariposas monarca realizan una migración masiva de miles de kilómetros desde canadá hasta méxico orientándose mediante la posición del sol y un reloj biológico interno. Los erizos de tierra son inmunes al veneno de muchas víboras lo que les permite comer pequeños reptiles venenosos sin sufrir daño alguno en su organismo."
];

document.addEventListener('scroll', handleScroll);

function handleScroll(event) {
  let p = document.createElement('p');
  p.textContent = datosAnimales[Math.floor(Math.random()*datosAnimales.length)];
  document.body.append(p);
}
